### ISSUE TITLE
How to run Skippy system

### ISSUE THREAD

**Issue by GitHubDiom** [edgerun/faas-sim#3]
Hi Thomas,

Could you please tell me that why this Skippy can not run?

I clone the faas-sim project,

and copy the skippy file (in skippy-core project) to faas-sim project.

but when I try to run the `faassim/cli/perf.py`, I got this error:

```
Traceback (most recent call last):
  File "/Users/jairwu/resources/faas-sim/faassim/cli/test_package.py", line 2, in <module>
    from faassim.faas import BadPlacementException
  File "/Users/jairwu/resources/faas-sim/faassim/cli/faassim.py", line 12, in <module>
    from faassim.faas import BadPlacementException
ModuleNotFoundError: No module named 'faassim.faas'; 'faassim' is not a package

```
-------- I solve the above problem by change the name of faassim file (under faassim dir) to faassimulation, and covert the corresponding "import".--------

but still, get an error when i try to run `faassim/cli/perf.py`
```
num_constraints,num_nodes,sampling,duration
Traceback (most recent call last):
  File "/Users/jairwu/resources/faas-sim/faassim/cli/perf.py", line 126, in <module>
    main()
  File "/Users/jairwu/resources/faas-sim/faassim/cli/perf.py", line 97, in main
    run_experiment(100, sched_params)
  File "/Users/jairwu/resources/faas-sim/faassim/cli/perf.py", line 107, in run_experiment
    t = synth.create_topology()
  File "/Users/jairwu/resources/faas-sim/faassim/scenarios.py", line 276, in create_topology
    raise ValueError
ValueError
```

**Comment by thrau** [comment]
hi, happy you're interested! yes unfortunately the code is a bit of a mess right now, and we're going to change a lot in the upcoming weeks.

here's how you can run a scenario:


* clone [skippy-core](https://github.com/edgerun/skippy-core/)
* run `make install` in skippy-core
* create a virtual environment in faas-sim and activate it
* in faas-sim, run `pip install -e ../skippy-core` (or the path where skippy-core is)
* then in faas-sim run `python -m faassim.main2`

check out [main2.py](https://github.com/edgerun/faas-sim/blob/master/faassim/main2.py) and you can change the run parameters there.

[main3.py](https://github.com/edgerun/faas-sim/blob/master/faassim/main3.py) creates the scalability results we used for the skippy paper!

**Comment by GitHubDiom** [comment]
@thrau Thanks Thomas,

After I run the command: `python -m faassim.main2`, the console gets
```
INFO:__main__:initializing scenario
INFO:faassim.net:creating bandwidth graph took 13.7432 seconds
```
Nothing else print

It seems trap in a `while` loop, is that expected?

**Comment by thrau** [comment]
yes it runs [10 runs](https://github.com/edgerun/faas-sim/blob/master/faassim/main2.py#L102) for each scheduler on a fairly large topology. This line [here](https://github.com/edgerun/faas-sim/blob/master/faassim/main2.py#L94) creates the [`CloudRegionsScenario`](https://github.com/edgerun/ether/blob/master/ether/scenarios/cloudregions.py) and you could reduce the number of nodes/regions it creates.

HTH
