### ISSUE TITLE
Is any possible for simulating the replcemet/delay commitment process? 

### ISSUE THREAD

**Issue by GitHubDiom** [edgerun/faas-sim#4]
I would like to implement MyPriority (in `skippy.core.priorities`)

The information I need is the utilization history of a specific node 

I found that it can retrieve by `RuntimeLogger().records`

But it looks like I can't do that because the utilization history(`RuntimeLogger().records`) aren’t recorded yet while running MyPriority

So I suppose that it will be OK (used utilization history while processing MyPriority) while processing the reassignment

Is that have possible?

Thank you

**Comment by thrau** [comment]
there is no real runtime utilization model at the moment. but you can add your own. @phip123 has significantly extended the simulator over the past months and the extensions include a model for resource utilization. we are in the process of open sourcing everything.
